// Date: 2014/11/09 5:34:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelfatcat extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer tail;
    ModelRenderer frontLeftLeg;
    ModelRenderer frontRightLeg;
    ModelRenderer backLeftLeg;
    ModelRenderer backRightLeg;
    ModelRenderer head;
  
  public Modelfatcat()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("head.main", 0, 0);
    setTextureOffset("head.ear1", 58, 0);
    setTextureOffset("head.ear2", 58, 2);
    
      body = new ModelRenderer(this, 8, 7);
      body.addBox(0F, 0F, 0F, 14, 11, 14);
      body.setRotationPoint(-8F, 10F, -6F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 0, 13);
      tail.addBox(-2F, 0F, -2F, 4, 3, 4);
      tail.setRotationPoint(-1F, 14F, 7F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      setRotation(tail, 1.660128F, 0F, 0F);
      frontLeftLeg = new ModelRenderer(this, 50, 0);
      frontLeftLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      frontLeftLeg.setRotationPoint(3F, 20F, -4F);
      frontLeftLeg.setTextureSize(64, 32);
      frontLeftLeg.mirror = true;
      setRotation(frontLeftLeg, 0F, 0F, 0F);
      frontRightLeg = new ModelRenderer(this, 42, 0);
      frontRightLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      frontRightLeg.setRotationPoint(-5F, 20F, -4F);
      frontRightLeg.setTextureSize(64, 32);
      frontRightLeg.mirror = true;
      setRotation(frontRightLeg, 0F, 0F, 0F);
      backLeftLeg = new ModelRenderer(this, 34, 0);
      backLeftLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      backLeftLeg.setRotationPoint(3F, 20F, 6F);
      backLeftLeg.setTextureSize(64, 32);
      backLeftLeg.mirror = true;
      setRotation(backLeftLeg, 0F, 0F, 0F);
      backRightLeg = new ModelRenderer(this, 0, 21);
      backRightLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      backRightLeg.setRotationPoint(-5F, 20F, 6F);
      backRightLeg.setTextureSize(64, 32);
      backRightLeg.mirror = true;
      setRotation(backRightLeg, 0F, 0F, 0F);
    head = new ModelRenderer(this, "head");
    head.setRotationPoint(-1F, 15F, -5F);
    setRotation(head, 0F, 0F, 0F);
    head.mirror = true;
      head.addBox("main", -5F, -3F, -4F, 10, 6, 5);
      head.addBox("ear1", -4F, -4F, -3F, 2, 1, 1);
      head.addBox("ear2", 2F, -4F, -3F, 2, 1, 1);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    tail.render(f5);
    frontLeftLeg.render(f5);
    frontRightLeg.render(f5);
    backLeftLeg.render(f5);
    backRightLeg.render(f5);
    head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
